## Basic LAb _ 01 _ Deep Learning 

Theory :  

 -> A tensor is the basic data structure in PyTorch (similar to NumPy arrays but with GPU support).

Tensors can be 0D (scalar), 1D (vector), 2D (matrix), or higher dimensional.

PyTorch tensors have:

Shape

Data type (dtype)

Device (CPU/GPU)

Common initialization Methods are : 
''' torch.tensor() 

- torch.zeros() 

- torch.ones()

- torch.rand()
- torch.arange()  '''


- ## 1.a) Create the Tensors 

In [ ]:
import torch

                                                         # Scalar tensor
a = torch.tensor(5)
print(a)

                                                        # Vector
b = torch.tensor([1, 2, 3])
print(b)

                                                         # Matrix
c = torch.tensor([[1, 2], [3, 4]])
print(c)

                                                      # Zeros, Ones, Random
z = torch.zeros(2, 3)
o = torch.ones(2, 3)
r = torch.rand(2, 3)

print(z)
print(o)
print(r)

                                                          # Data types
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.int64)

print(x.dtype)
print(y.dtype)


tensor(5)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3760, 0.9599, 0.1821],
        [0.5007, 0.2101, 0.0217]])
torch.float32
torch.int64


- ## b) Tensor operations: arithmetic, broadcasting, indexing, reshaping

In [2]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Arithmetic operations
print(a + b)
print(a * b)

# Broadcasting
c = torch.tensor([[1], [2], [3]])
d = torch.tensor([10, 20, 30])
print(c + d)

# Indexing
e = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(e[0])
print(e[0][1])

# Reshaping
f = torch.arange(6)
f = f.reshape(2, 3)
print(f)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
tensor([1, 2, 3])
tensor(2)
tensor([[0, 1, 2],
        [3, 4, 5]])


 - ##  c) Automatic Differentiation using PyTorch Autograd

In [ ]:
x = torch.tensor(2.0, requires_grad=True) # here we enable gradient tracking using requires_grad=True
y = x**2 + 3*x + 1

y.backward()                             # here we have calculated the gradient of y w.r.t x

print("Gradient of y w.r.t x:", x.grad) 


Gradient of y w.r.t x: tensor(7.)


- ## 2) Perform all Linear Algebra Operations with TensorFlow

In [1]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Addition
print(tf.add(A, B))

# Multiplication
print(tf.matmul(A, B))

# Transpose
print(tf.transpose(A))

# Determinant
print(tf.linalg.det(A))

# Inverse
print(tf.linalg.inv(A))


RuntimeError: CPU dispatcher tracer already initlized

RuntimeError: CPU dispatcher tracer already initlized

RuntimeError: CPU dispatcher tracer already initlized

RuntimeError: CPU dispatcher tracer already initlized

RuntimeError: CPU dispatcher tracer already initlized

RuntimeError: CPU dispatcher tracer already initlized

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.   1. ]
 [ 1.5 -0.5]], shape=(2, 2), dtype=float32)


- ## 3) AND & OR Gates using Perceptron
       - Perceptron is a Single Layered NN . In this we have Weight sUM and the Activation function , at this Stage we just learned to Update the Weights of the Perceptron , But Still Backpropagation was not Introduced ...... it was introduced Later 

In [1]:
import numpy as np

def perceptron(x, w, b):
    z = np.dot(x, w) + b
    return 1 if z >= 0 else 0

# AND Gate
w_and = [1, 1]
b_and = -1.5

print("AND Gate")
for x in [[0,0],[0,1],[1,0],[1,1]]:
    print(x, perceptron(x, w_and, b_and))

# OR Gate
w_or = [1, 1]
b_or = -0.5

print("\nOR Gate")
for x in [[0,0],[0,1],[1,0],[1,1]]:
    print(x, perceptron(x, w_or, b_or))


AND Gate
[0, 0] 0
[0, 1] 0
[1, 0] 0
[1, 1] 1

OR Gate
[0, 0] 0
[0, 1] 1
[1, 0] 1
[1, 1] 1


- ## 4) XOR Problem using PyTorch Neural Network
        - XOR is not linearly separable

          - Requires hidden layer

            - Implemented using multi-layer neural network ''

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# XOR data
X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

for epoch in range(5000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

print("XOR Output:")
print(model(X).round())


XOR Output:
tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


- ## 5) Simple Neural Network for Regression Problem

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

#  regression data
X = torch.tensor([[1.0, 2.0],
                  [2.0, 3.0],
                  [3.0, 4.0],
                  [4.0, 5.0]])

y = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

class RegressionNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = self.output(x)
        return x

model = RegressionNet()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(2000):
    optimizer.zero_grad()
    prediction = model(X)
    loss = criterion(prediction, y)
    loss.backward()
    optimizer.step()

print("Predicted Output:")
print(model(X))


Predicted Output:
tensor([[3.0000],
        [5.0000],
        [7.0000],
        [9.0000]], grad_fn=<AddmmBackward0>)
